### ISSUE TITLE
[16.0] pms: Fallo en creación de asientos

### ISSUE THREAD

**Issue by syci** [commitsun/pms#190]
Al intentar crear factura o asiento falla el método https://github.com/commitsun/pms/blob/8f854d162aef2af7ec1d55f63ea39504baf27325/pms/models/account_move.py#L188

En 16 no tiene parámetros, habría que ajustar el método.

**Comment by DarioLodeiros** [comment]
https://github.com/commitsun/pms/commit/863c1be2a55ad8254cae4b5a29a186faeee84d1f

queda el flujo de facturación completo, desactivando provisionalmente algunas funcionalidades hasta la revisión final
