### ISSUE TITLE
[16.0] pms: Fallo en vista  pms.pms_property_views_form

### ISSUE THREAD

**Issue by syci** [commitsun/pms#191]
Los campos de correo se ven mal:

![image](https://github.com/user-attachments/assets/82f38602-03a8-484b-a0c2-2b8389daccee)

**Comment by DarioLodeiros** [comment]
Gracias! Queda corregido: https://github.com/commitsun/pms/commit/ae11a644fbba771d15e25eb614226dc90ccc5681
