### ISSUE TITLE
[16.0][MIG] connector_pms: Clase obsoleta

### ISSUE THREAD

**Issue by syci** [commitsun/pms#202]
https://github.com/commitsun/pms/blob/e9a1352ac7ffbc16c099d0cc28deadaf0ba15d8c/connector_pms/components_custom/mapper.py#L32

- Antes (obsoleto en Python 3.10+)
from collections import Callable
- Después (compatible con Python 3.10+)
from collections.abc import Callable

**Comment by DarioLodeiros** [comment]
Fixed: https://github.com/commitsun/pms/commit/f289c163647e524d4b2ade3276089855decd9afd
